name: Echo Pipeline

on: push

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - name: Echo message
      run: |
        echo "Hello, world!"
        echo "This is a simple pipeline with echo statements."
        echo "You can customize this pipeline by adding more steps."
