name: JFrogUploadArtifact3

on:
  push:
    branches:
      - main

jobs:
  upload_to_jfrog:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "/home/runner/work/jenkins-test/jenkins-test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: "https://devopsidc2.jfrog.io"
          JF_USER: "devops"
          JF_PASSWORD: "DevOps1!"
    
      - name: Run JFrog CLI Ping
        run: |
          export JFROG_CLI_HOME="/home/runner/work/jenkins-test/jenkins-test"
          jf rt ping 
          jf --version
          jf rt u "README.md" "local_repo"
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          jf rt bp --dry-run  > jfrog_build_info.json
          # Publish build info
          jf rt bp
      - name: Add Messages to Check Run Output
        uses: actions/github-script@v5
        with:
          github-token: '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'
          script: |
            const { owner, repo } = context.repo;
            // Specify the check run's ID you want to update
            const checkRunId = context.runId;

            const messagesToAdd = [
              "Message 1: This is the first message.",
              "Message 2: This is the second message.",
            ];

            // Update the check run's output by adding messages
            const currentOutput = {
              title: 'My Check Run Output',
              summary: 'This is the summary of the check run.',
              text: messagesToAdd.join('\n\n'), // Combine messages with line breaks
            };
            console.log('Check Run ID:', checkRunId);
            console.log('Owner:', owner);
            console.log('Repo:', repo);

            await github.checks.update({
              owner,
              repo,
              check_run_id: checkRunId,
              output: currentOutput,
            });


              
      
