name: JFrogUploadArtifact

on:
  push:
    branches:
      - main

jobs:
  upload_to_jfrog:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "/home/runner/work/jenkins-test/jenkins-test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: "https://devopskiran002.jfrog.io/"
          JF_USER: "admin"
          JF_PASSWORD: "Testing1!"
    
      - name: Run JFrog CLI Ping
        run: |
          export JFROG_CLI_HOME="/home/runner/work/jenkins-test/jenkins-test"
          jf rt ping 
          jf --version
          jf rt u "README.md" "local_repo"
          # Collect environment variables for the build
          #jf rt bce
          # Collect VCS details from git and add them to the build
          #jf rt bag
          jf rt bp --dry-run 
          jf rt bp --dry-run  > jfrog_build_info.json
          jf rt bce
          # Publish build info
          jf rt bp

  changeApproval:
    name: ServiceNow Change Approval
    needs: upload_to_jfrog
    runs-on: ubutun-latest

    steps:     
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@v3.1.0
        id: create
        with:
          devops-integration-token: https://sampath11.service-now.com/
          instance-url: "https://sampath11.service-now.com/"
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approval'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
          interval: '100'
          timeout: '3600'
          changeCreationTimeOut: '3600'
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: true
      - name: Output of Change Creation
        run: echo "change-request-number = ${{ steps.create.outputs.change-request-number }} and change-request-sys-id = ${{ steps.create.outputs.change-request-sys-id }} " >> $GITHUB_OUTPUT
    
  deploy:
    name: Deploy
    needs: changeApproval
    runs-on: ubutun-latest

    steps:     
      - name: Run Deployment Script
        run: echo "Deployment Finished....."
