name: JFrog CLI Ping

on:
  push:
    branches:
      - main

jobs:
  jfrog_ping:
    runs-on: ubuntu-latest

    env:
      JF_URL: ${{ env.JFROG_URL }}
      JF_USER: ${{ env.JFROG_USER_NAME }}
      JF_PASSWORD: ${{ env.JFROG_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          url: ${{ env.JF_URL }}
          username: ${{ env.JF_USER }}
          password: ${{ env.JF_PASSWORD }}

      - name: Run JFrog CLI Ping
        run: |
          jfrog rt ping
