name: JFrogUploadArtifact2 

on:
  push:
    branches:
      - main

jobs:
  upload_to_jfrog:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "/home/runner/work/jenkins-test/jenkins-test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JF_URL: "https://devopskiran002.jfrog.io/"
          JF_USER: "admin"
          JF_PASSWORD: "Testing1!"
    
      - name: Upload artifacts to jfrog
        run: |
          export JFROG_CLI_HOME="/home/runner/work/jenkins-test/jenkins-test"
          jf rt ping 
          jf --version
          jf rt u "README.md" "local_repo"
          # Publish build info
          jf rt bp
      - name: download artifacts to jfrog
        run: |
          export JFROG_CLI_HOME="/home/runner/work/jenkins-test/jenkins-test"
          jf rt ping 
          jf --version
          jf rt dl "local_repo/README.md" ./
          # Publish build info
          jf rt bp
    
