name: JFrog CLI Ping

on:
  push:
    branches:
      - main

jobs:
  jfrog_ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          echo "$(pwd)/jfrog" >> $GITHUB_PATH

      - name: Set up JFrog CLI
        run: |
          $(pwd)/jfrog config add --url https://devopsidc2.jfrog.io --user devops --password DevOps1!
          $(pwd)/jfrog rt ping
