name: JFrog CLI Ping

on:
  push:
    branches:
      - main

jobs:
  jfrog_ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          echo "$HOME/.jfrog/cli/jfrog" >> $GITHUB_PATH
          echo "$HOME/.jfrog/cli/jfrog"
          echo "GITHUB PATH===$GITHUB_PATH"

      - name: Set up JFrog CLI
        run: |
          $HOME/.jfrog/cli/jfrog config add --url https://devopsidc2.jfrog.io --user devops --password DevOps1!
          $HOME/.jfrog/cli/jfrog rt ping
